name: Second Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  echo_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Second step
        run: 'echo now deploying branch: $GITHUB_REF_NAME to the test server'
