name: code_quality
on:
  push:
    branches:
      - 'main'

env:
  WELCOME_PHRASE: Hello

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: 'Say Hello'
        run: echo "$WELCOME_PHRASE"
      - name: npm install
        run: npm install
      - name: npm lint
        run: npm run lint
      - name: unit test
        run: npm test
